# Generated by Django 2.2.2 on 2019-06-27 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jobName', models.CharField(max_length=200)),
            ],
        ),
        migrations.DeleteModel(
            name='Jobs',
        ),
    ]
