# Generated by Django 2.2.2 on 2019-06-27 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0002_auto_20190627_2028'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='isCompleted',
            field=models.BooleanField(default=False),
        ),
    ]
