# Generated by Django 2.2.2 on 2019-06-27 21:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0003_job_iscompleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='dateAdded',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Time'),
            preserve_default=False,
        ),
    ]
