# Generated by Django 2.2.2 on 2019-06-27 21:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0004_job_dateadded'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='dateAdded',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='Time'),
        ),
        migrations.AlterField(
            model_name='job',
            name='jobName',
            field=models.CharField(max_length=200, verbose_name='Job Name'),
        ),
    ]
