# Generated by Django 2.2.2 on 2019-06-28 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0005_auto_20190627_2143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='jobName',
            field=models.CharField(default='', max_length=200, verbose_name='Job Name'),
        ),
    ]
