# Generated by Django 4.0.1 on 2022-12-24 03:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('to_do_list', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarefa',
            name='data',
            field=models.DateField(blank=True, default=datetime.datetime(2022, 12, 24, 0, 41, 54, 367897)),
        ),
    ]
