# Generated by Django 4.0.1 on 2022-12-26 22:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('to_do_list', '0002_alter_tarefa_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tarefa',
            name='data',
        ),
        migrations.AddField(
            model_name='tarefa',
            name='data_de_conclusao',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
