# Generated by Django 4.1.5 on 2023-01-05 15:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('to_do_list', '0003_remove_tarefa_data_tarefa_data_de_conclusao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarefa',
            name='data_de_conclusao',
            field=models.DateField(blank=True, default=datetime.date.today, null=True),
        ),
    ]
